In [49]:
import pandas as pd
import numpy as np
import sklearn
from sklearn import linear_model

In [50]:
data = pd.read_csv("/content/student.csv", sep=";")
data = data[["G1","G2","G3", "studytime", "failures"]]
data

G1  G2  G3  studytime  failures
0     5   6   6          2         0
1     5   5   6          2         0
2     7   8  10          2         3
3    15  14  15          3         0
4     6  10  10          2         0
..   ..  ..  ..        ...       ...
390   9   9   9          2         2
391  14  16  16          1         0
392  10   8   7          1         3
393  11  12  10          1         0
394   8   9   9          1         0

[395 rows x 5 columns]

In [51]:
predict ="G3"
X=np.array(data.drop([predict],axis=1))
y=np.array(data[predict])


In [52]:
X

array([[ 5,  6,  2,  0],
       [ 5,  5,  2,  0],
       [ 7,  8,  2,  3],
       ...,
       [10,  8,  1,  3],
       [11, 12,  1,  0],
       [ 8,  9,  1,  0]])

In [53]:
y

array([ 6,  6, 10, 15, 10, 15, 11,  6, 19, 15,  9, 12, 14, 11, 16, 14, 14,
       10,  5, 10, 15, 15, 16, 12,  8,  8, 11, 15, 11, 11, 12, 17, 16, 12,
       15,  6, 18, 15, 11, 13, 11, 12, 18, 11,  9,  6, 11, 20, 14,  7, 13,
       13, 10, 11, 13, 10, 15, 15,  9, 16, 11, 11,  9,  9, 10, 15, 12,  6,
        8, 16, 15, 10,  5, 14, 11, 10, 10, 11, 10,  5, 12, 11,  6, 15, 10,
        8,  6, 14, 10,  7,  8, 18,  6, 10, 14, 10, 15, 10, 14,  8,  5, 17,
       14,  6, 18, 11,  8, 18, 13, 16, 19, 10, 13, 19,  9, 16, 14, 13,  8,
       13, 15, 15, 13, 13,  8, 12, 11,  9,  0, 18,  0,  0, 12, 11,  0,  0,
        0,  0, 12, 15,  0,  9, 11, 13,  0, 11,  0, 11,  0, 10,  0, 14, 10,
        0, 12,  8, 13, 10, 15, 12,  0,  7,  0, 10,  7, 12, 10, 16,  0, 14,
        0, 16, 10,  0,  9,  9, 11,  6,  9, 11,  8, 12, 17,  8, 12, 11, 11,
       15,  9, 10, 13,  9,  8, 10, 14, 15, 16, 10, 18, 10, 16, 10, 10,  6,
       11,  9,  7, 13, 10,  7,  8, 13, 14,  8, 10, 15,  4,  8,  8, 10,  6,
        0, 17, 13, 14,  7

In [68]:
x_train, x_test, y_train, y_test= sklearn.model_selection.train_test_split(X, y, test_size=0.1)

y_test


array([15, 12, 11, 10, 11, 15, 14, 16, 10,  0, 11, 14,  6, 17, 15, 14, 12,
       14, 18,  0, 11, 13,  9, 12, 13,  0, 10, 10, 14, 12, 11, 16,  9,  5,
       12, 19,  8, 10,  0, 14])

In [69]:
x_test

array([[13, 15,  4,  0],
       [ 8, 12,  1,  0],
       [ 8,  8,  1,  0],
       [ 8, 10,  1,  0],
       [11, 11,  3,  0],
       [14, 15,  2,  0],
       [14, 14,  1,  0],
       [13, 15,  2,  0],
       [11, 11,  3,  0],
       [ 8,  8,  2,  0],
       [10, 10,  2,  0],
       [15, 12,  3,  0],
       [ 7,  6,  2,  0],
       [16, 15,  4,  0],
       [16, 15,  2,  0],
       [11, 14,  1,  0],
       [12, 12,  1,  0],
       [13, 13,  2,  0],
       [16, 18,  2,  0],
       [ 9,  0,  2,  0],
       [ 8, 11,  2,  0],
       [15, 14,  2,  1],
       [10,  9,  3,  0],
       [12, 12,  4,  0],
       [16, 12,  1,  0],
       [10,  9,  4,  0],
       [11, 10,  2,  1],
       [10, 10,  1,  0],
       [14, 13,  3,  0],
       [13, 12,  2,  1],
       [12, 10,  2,  0],
       [18, 16,  3,  0],
       [10,  9,  3,  1],
       [ 8,  6,  2,  2],
       [13, 12,  1,  0],
       [19, 18,  3,  0],
       [ 9,  8,  2,  0],
       [ 6, 10,  2,  0],
       [10,  0,  2,  0],
       [10, 13,  1,  0]])

In [70]:
y_train

array([10, 11,  0, 12, 15, 18,  0,  8, 18, 15, 10,  9, 14, 11, 13, 14, 11,
        9, 14,  8, 11, 10, 15, 18,  8, 10, 11, 12, 11,  0, 16,  9,  8, 18,
       11,  9, 13,  8, 10,  0,  7, 10, 13, 14, 13,  8, 14, 12, 12,  9, 13,
        5, 11, 20, 18, 11,  8,  9, 11, 15, 11,  8,  8,  7,  0,  8, 16, 12,
       11, 10, 15, 15,  0,  0,  0, 16, 11, 14, 11,  0, 11, 11, 12, 11, 13,
       15, 11, 10, 14,  6, 11, 10, 11, 10, 10, 13, 18, 14,  5,  9, 12,  7,
       14, 16, 19, 10,  6, 11, 11,  5, 17, 16,  7, 12,  8,  0,  0, 11,  0,
        8,  6, 19,  9, 10, 11,  8, 14,  9,  0,  7,  9, 15, 15,  9, 11,  9,
       13, 11,  0,  0, 12, 17, 13, 10, 10,  0,  9, 14, 10, 10,  6,  8,  0,
       10, 13,  6,  0, 18, 16,  0,  9, 16, 12,  8, 13,  7, 10, 13, 10, 10,
       12, 10, 11, 11, 12, 11, 15, 15, 10,  8,  9, 11, 13, 15, 14, 13, 10,
       17, 13,  0, 10, 15, 14, 16, 10, 12,  9, 14, 12, 12, 10, 14, 10, 12,
        8, 14,  9, 12,  7,  6, 10, 11,  9, 18,  8,  8,  8, 10,  7, 12,  0,
       18, 13,  8, 10, 10

In [71]:
x_train

array([[11,  9,  3,  0],
       [13, 13,  2,  0],
       [ 6,  0,  1,  0],
       ...,
       [11, 10,  3,  0],
       [ 7,  6,  2,  0],
       [11, 11,  1,  0]])

In [77]:
linear=linear_model.LinearRegression()
linear.fit(X,y)
accuracy =linear.score(X,y)

In [86]:
predictions=linear.predict(X)
predictions

array([ 5.01844732,  4.04191939,  6.48316985, 14.13737848,  9.07489666,
       15.31057504, 11.92997835,  4.19225703, 18.39049646, 15.1602374 ,
        7.72319137, 11.43263443, 14.38037812,  9.67624722, 15.94009669,
       14.38037812, 13.8367032 ,  9.37557194,  3.59991708,  9.57224058,
       14.03337184, 15.05623076, 15.31057504, 13.05684391,  8.50305065,
        7.76903164, 12.12664699, 16.48377161, 10.80311278, 11.62930307,
       10.5024375 , 16.58777825, 16.58777825,  9.37557194, 14.07970284,
        6.64265681, 16.09043433, 16.09043433, 11.73330971, 13.4038502 ,
        8.96223143, 12.12664699, 18.84150938,  7.61918473,  9.41324435,
        7.42251609, 11.77964071, 19.42470002, 15.31057504,  6.03264766,
       12.90650627, 12.75616863, 10.73677856,  9.57224058, 12.80249963,
        8.39904401, 15.1602374 , 15.1602374 ,  9.52590958, 16.28710297,
       10.65277514,  7.91986001,  9.37557194,  8.50305065,  9.67624722,
       15.46091269, 12.66350663,  5.90231324,  8.39904401, 16.04

In [87]:
for x in range(len(predictions)):
  print(predictions[x],X[x],y[x])

5.018447317561067 [5 6 2 0] 6
4.041919393158161 [5 5 2 0] 6
6.4831698525555765 [7 8 2 3] 10
14.137378478158585 [15 14  3  0] 15
9.074896655921803 [ 6 10  2  0] 10
15.310575044678318 [15 15  2  0] 15
11.929978349222269 [12 12  2  0] 11
4.1922570339072704 [6 5 2 0] 6
18.390496458636143 [16 18  2  0] 19
15.160237403929207 [14 15  2  0] 15
7.723191370112426 [10  8  2  0] 9
11.432634425607224 [10 12  3  0] 12
14.38037812164313 [14 14  1  0] 14
9.67624721891824 [10 10  2  0] 11
15.94009668621529 [14 16  3  0] 16
14.38037812164313 [14 14  1  0] 14
13.836703196660366 [13 14  3  0] 14
9.375571937420021 [ 8 10  2  0] 10
3.599917080714574 [6 5 1 3] 5
9.572240579536848 [ 8 10  1  0] 10
14.033371838777194 [13 14  2  0] 15
15.056230764547815 [12 15  1  0] 15
15.310575044678318 [15 15  2  0] 16
13.056843914374285 [13 13  2  0] 12
8.503050652398505 [10  9  3  0] 8
7.769031643429374 [6 9 1 2] 8
12.126646991339097 [12 12  1  0] 11
16.48377161119805 [15 16  1  0] 15
10.803112784070256 [11 11  2  0] 11
11